#!/bin/bash -ex

#create directories to store mysql configuration and delete any reused files from previous units.

mkdir -p  /var/www/html
chown -R www-data:www-data /var/www/html

juju-log "Installing packages"

apt-get update -qq
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 mysql-client-core-5.5 php5-mysql pwgen

# Configure apache
juju-log "Enabling apache modules: rewrite, vhost_alias, php5"

a2enmod rewrite vhost_alias
a2enmod php5 headers
a2dissite 000-default

service apache2 restart

#opening port 80
juju-log "Exposing apache2 service"

relation-set port=80 hostname=`hostname -f`

open-port 80/tcp